### PR TITLE
fix/xcode_14_build_error

### PR DESCRIPTION
**Pull request by kadirbekar**
Platform ios updated to 14 in Podfile

### CODE REVIEW

**Comment by Henryhehe** [comment]
got this error after this change

```
Error (Xcode): Building for iOS Simulator, but linking in object file built for
iOS, file
'/Users/henryhe/development/flutter-wonderous-app/ios/Pods/GoogleMaps/Base/Frame
works/GoogleMapsBase.framework/GoogleMapsBase' for architecture arm64


Could not build the application for the simulator.
Error launching application on iPhone 14.
```

**Comment by nguyen703** [comment]
@Henryhehe 
did you try running this with real device? The message says that you encountered the problem while running on an emulator.

@kadirbekar 
This works! Thank you a lot ;)

**Comment by kadirbekar** [comment]
> @Henryhehe did you try running this with real device? The message says that you encountered the problem while running on an emulator.
> 
> @kadirbekar This works! Thank you a lot ;)

You are welcome :)

**Comment by esDotDev** [comment]
Just tested today and I'm not seeing an error in xcode 14, I don't think this is needed anymore?

**Pull request closed without merging**
